on:
   schedule:
    # runs every day at 5:00 AM UTC in jan, feb, sep-dec
     - cron:  '0 5 * 1,2,9-12 *'
   repository_dispatch:
      types: [buildpatch]
   workflow_dispatch:

name: update_pbp_patch

jobs:
  update:
    name: update_pbp_patch
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
           cache-version: 1
           extra-packages: |
            nflverse/nflfastR
            nflverse/nflreadr
            nflverse/nflverse-data
            nflverse/ngsscrapR
            nflverse/fastrmodels
            ropensci/piggyback

      - name: Run pbp patch update
        run: Rscript -e 'source("R/update_pbp_patch.R")'
