on:
  schedule:
    # runs every day at 9:00 AM UTC in jan, feb, sep-dec
    - cron:  '0 9 * 1,2,9-12 *'
  workflow_dispatch:

name: update_current_season_pbp_and_stats

jobs:
  update:
    name: update_pbp
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
           cache-version: 1
           extra-packages: |
            nflverse/nflfastR
            nflverse/nflreadr
            nflverse/nflverse-data
            ropensci/piggyback

      - name: Run pbp update
        run: Rscript -e 'source("R/update_current_season_pbp.R")'

      - name: Run player_stats script
        run: Rscript -e 'source("R/save_stats.R")'

      - name: Run player_stats_kicking script
        run: Rscript -e 'source("R/update_ps_kicks.R")'
