on:
  push:
    paths:
      - 'lateral_yards/multiple_lateral_yards.csv'
  workflow_dispatch:

name: Release update lateral yards

jobs:
  update:
    name: Release update lateral yards
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
           cache-version: 1
           extra-packages: |
            nflverse/nflverse-data
            ropensci/piggyback

      - name: Run laterals update
        run: Rscript -e 'source("R/update_multiple_laterals.R")'
