name: Setup nflverse Update

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            nflverse/nflfastR
            nflverse/nflreadr
            nflverse/nflverse-data
            nflverse/fastrmodels
            ropensci/piggyback
