on: workflow_dispatch

name: GHA test

jobs:
  gha_test:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.NFLVERSE_GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
           cache-version: 1
           extra-packages: |
            nflverse/nflfastR
            nflverse/nflreadr
            nflverse/nflverse-data
            ropensci/piggyback

      - name: Run update script
        run: |
          writeLines(paste0("export NFLFASTR_VERSION=",as.character(packageVersion("nflfastR"))),".ver")
          writeLines(as.character(runif(1)),"blob.txt")
          nflversedata::nflverse_upload("blob.txt","pbp")
        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          source .ver
